name: Ksu
on:
  workflow_dispatch:

jobs:
  ci-test:
    name: ci-ksu
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Ksu CI
      uses: ./
      with:
          kernel-url: https://github.com/OnePlusOSS/android_kernel_5.10_oneplus_mt6983
          kernel-dir: kernel
          depth: 1
          vendor: true
          vendor-url: https://github.com/OnePlusOSS/android_kernel_modules_oneplus_mt6983
          kernel-branch: oneplus/mt6983_v_15.0.0_ace_2v
          vendor-branch: oneplus/mt6983_v_15.0.0_ace_2v
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r416183b
          lxc: true
          lxc-patch: true
          nethunter: true
          bbrplus: true
          anykernel3: true
